version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER:
      POSTGRES_PASSWORD:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER:
      DB_SCHEMA: public
      DB_PASSWORD:
      KEYCLOAK_USER:
      KEYCLOAK_PASSWORD:
    ports:
      - 8080:8080
    depends_on:
      - postgres
